[env]
TERM = "xterm-256color"

import = "~/.config/alacritty/tokyo-night.toml"

[window]
dimensions.columns = 150
dimensions.lines = 50

padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.85
blur = true

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 0


[colors]
[colors.primary]
background = "0x282c34"
foreground = "0xf8f8f2"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -s main; exec /bin/zsh"]
